"""Add truck frontend fields

Revision ID: 8a8d0352d0d0
Revises: 915912c960bb
Create Date: 2026-09-14 19:55:12.200151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8d0352d0d0'
down_revision: Union[str, None] = '915912c960bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('status', sa.String(), nullable=False))
    op.add_column('trucks', sa.Column('assigned_bills', sa.Integer(), nullable=False))
    op.add_column('trucks', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'is_archived')
    op.drop_column('trucks', 'assigned_bills')
    op.drop_column('trucks', 'status')
    # ### end Alembic commands ###
